version: '3'
services:
  web:
    build:
      dockerfile: web.dockerfile
      context: .
    image: awajo-web
    container_name: awujo-web
    ports:
      - 8080:8080
    volumes:
      - ./web:/var/www
    networks:
      - awujo-network

  api:
    build:
      dockerfile: api.dockerfile
      context: .
    image: awajo-api
    container_name: awujo-api
    ports:
      - 8081:8081
    volumes:
      - ./api:/var/www
    networks:
      - awujo-network
      
networks:
  awujo-network:
    driver: bridge
